### ISSUE TITLE
Translate folder of .vm files

### ISSUE THREAD

**Issue by wildmaples** [wildmaples/jack-virtual-machine#15]
We currently only accept single .vm files to be translated. It'd be cool to allow an entire folder to be translated.

**Comment by tomstuart** [comment]
This will be a blocker once #17 is merged, because the next project after `SimpleFunction` is [`FibonacciElement`](https://github.com/wildmaples/nand2tetris/tree/master/projects/08/FunctionCalls/FibonacciElement), which requires us to translate a directory containing two `.vm` files into a single `.asm` file.

From [`FibonacciElement.tst`](https://github.com/wildmaples/nand2tetris/blob/master/projects/08/FunctionCalls/FibonacciElement/FibonacciElement.tst#L6-L7):

> // FibonacciElement.asm results from translating both Main.vm and Sys.vm into
> // a single assembly program, stored in the file FibonacciElement.asm.
